version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: monthly
    allow:
      - dependency-name: "dependencies/2decomp-fft"
      - dependency-name: "dependencies/cuDecomp"
      - dependency-name: "dependencies/diezDecomp"
  - package-ecosystem: github-actions
    directories:
      - "/"
      - "/.github/actions/build"
    schedule:
      interval: weekly
    groups:
      actions-all:
        patterns:
          - "*"
