version: 2
updates:
  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: monthly
    allow:
      - dependency-name: "dependencies/cuDecomp"
      - dependency-name: "dependencies/diezDecomp/diezDecomp-repo"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      actions-all:
        patterns:
          - "*"
