name: run-all

on:
  workflow_dispatch:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    types:
    - opened
    - reopened
    - synchronize
    - ready_for_review

jobs:
  GNU:
    uses: ./.github/workflows/run-one.yml
    with:
      compiler: "GNU"
      container_image: "gcc:latest"

  INTEL:
    uses: ./.github/workflows/run-one.yml
    with:
      compiler: "INTEL"
      container_image: "intel/oneapi-hpckit:latest"

  NVIDIA:
    uses: ./.github/workflows/run-one.yml
    with:
      compiler: "NVIDIA"
      container_image: "nvcr.io/nvidia/hpc-sdk:latest"
